### ISSUE TITLE
Parameter -I not allowed

### ISSUE THREAD

**Issue by dantemorius** [ICTU/zap-baseline#19]
Using the default image from owasp repo, the parameter -I (UPPERCASE i) allows to go ahead with Pipeline without mark it as Failed, but with this image, the job always break. I would like to have the option of generate the Scan report without interrupt the Pipeline.

Is there any way to workaround this?

**Comment by dicksnel** [comment]
Hi, -I is only used to return exit code 0 if ZAP has detected a warning. If you do not use -I, it would return exit code 1, which will break your job.

If your job breaks, the authentication part is probably throwing an exception because for example the logon fails. Can you post the log of the job that breaks?
